In [1]:
# Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output should be
#    array([[ 0.,  1.,  0.],
#              [ 0.,  0.,  1.],
#              [ 0.,  1.,  0.],
#              [ 0.,  1.,  0.],
#              [ 0.,  1.,  0.],
#             [ 1.,  0.,  0.]])
import numpy as np
arr = np.array([2, 3, 2, 2, 2, 1])
max=0
for i in arr:
    if i > max:
        max=i

arr2=np.zeros((len(arr),max))
for i in range(0,len(arr)):
    for j in range(0,max):
        if arr[i] == j+1:
            arr2[i][j]=1
print(arr2)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [2]:
# 2.Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) 
# Desired Output: array([ 1.,2.,3.,5.,6.,7.])
arr=np.array([1,2,3,np.nan,5,6,7,8,np.nan])

print(arr[~np.isnan(arr)])

[1. 2. 3. 5. 6. 7. 8.]


In [3]:
# 3.Find Local maxima from an array. Input:
# a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
diff = np.diff(a)

for i in range(0,len(diff)):
    if diff[i]<-1:
        print(i)


2
5


In [ ]:
# 4.From the given 1d array arr, generate a 2d matrix using strides,
# For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with 
# a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]
# w and s will be provided by user
def print_matrix(arr, w, s):
    ans = []
    for i in range(0, len(arr), s):
        temp = []
        for k in range(w):
            if i+k >= len(arr):
                temp.append(0)
            else:
                temp.append(arr[i+k])
        ans.append(temp)

    return ans

arr = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
w = int(input())
s = int(input())
print(print_matrix(arr, w, s))